version: '3.8'

services:
  crm-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
